Documentation:
  Enabled: false
Lint/MissingSuper:
  Exclude:
    - 'services/**/*'
    - 'core/**/*'
Metrics/ClassLength:
  Enabled: false
  CountComments: false
  Max: 1000
Metrics/MethodLength:
  Max: 100
Metrics/AbcSize:
  Max: 500
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/PerceivedComplexity:
  Max: 30
Metrics/ModuleLength:
  Max: 300
Metrics/BlockLength:
  Max: 100
Naming/VariableNumber:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
