AllCops:
  NewCops: enable
  DisplayStyleGuide: true
  DisplayCopNames: true
  SuggestExtensions: false
  Include:
    - 'app/controllers/**/*.rb'
    - 'app/models/**/*.rb'
  Exclude:
    - '**/bin/spring'
    - '**/bin/setup'
    - '**/bin/rake'
    - '**/bin/rails'
    - '**/db/schema.rb'
    - 'client/**/**'
    - 'config/**/**'
    - 'db/**/**'
    - 'bin/**'
    - 'app/models/role.rb'
    - 'vendor/*'
    - '**/Gemfile'
    - '**/Rakefile'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
