name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        run: |
          PR_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
          
          CHANGED_FILES=$(curl -sSL -H "$AUTH_HEADER" "$PR_URL" | jq -r '.[].filename')
          echo "Changed files in the pull request: $CHANGED_FILES" 

      - name: List all changed files
        run: |
          for file in $CHANGED_FILES; do
            echo "$file was changed"
          done
