name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        run: |
          PR_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
          
          CHANGED_FILES=$(curl -sSL -H "$AUTH_HEADER" "$PR_URL" | jq -r '.[].filename')
          echo "Changed files in the pull request: $CHANGED_FILES"

      - name: Install Bundler and RuboCop
        run: |
          gem install bundler
          bundle install

      - name: Run RuboCop for changed files
        run: |
          for file in $CHANGED_FILES; do
            if [[ $file == *".rb" ]]; then
              # Check if the file is a Ruby file
              echo "Running RuboCop for $file"
              bundle exec rubocop "$file"
            else
              echo "$file is not a Ruby file, skipping RuboCop"
            fi
          done
