name: RuboCop Check

on:
  pull_request:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Get changed Ruby files
        id: changed-files
        uses: actions/github-script@v5
        with:
          script: |
            const listChangedFiles = async () => {
              const response = await github.repos.compareCommits({
                base: context.payload.pull_request.base.sha,
                head: context.payload.pull_request.head.sha,
              });
              const files = response.data.files
                .filter(file => file.filename.endsWith('.rb'))
                .map(file => file.filename);
              return files;
            };
            return await listChangedFiles();
          result-encoding: 'string'

      - name: Run RuboCop on modified files
        run: |
          modified_files="${{ steps.changed-files.outputs.result }}"
          if [ -n "$modified_files" ]; then
            bundle exec rubocop $modified_files
          else
            echo "No modified Ruby files found."
          fi
