name: RuboCop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rubocop:
    name: Run RuboCop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install rubocop

      - name: Run RuboCop
        run: rubocop

      - name: Set RuboCop check status
        run: |
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          CHECK_NAME="RuboCop"

          STATUS=$(curl -s -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -d "{
              \"name\": \"${CHECK_NAME}\",
              \"head_sha\": \"${{ github.event.pull_request.head.sha }}\",
              \"status\": \"completed\",
              \"conclusion\": \"success\",
              \"completed_at\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\",
              \"output\": {
                \"title\": \"RuboCop\",
                \"summary\": \"RuboCop analysis completed successfully.\"
              }
            }" \
            "https://api.github.com/repos/${REPO}/check-runs")

          echo "Status response: $STATUS"
