name: RuboCop Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    env:
      CHANGED_FILES: ''

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Get changed files
        id: changed-files
        run: |
          PR_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
          
          export CHANGED_FILES=$(curl -sSL -H "$AUTH_HEADER" "$PR_URL" | jq -r '.[].filename' | grep '\.rb$')
          echo "Changed Ruby files in the pull request: $CHANGED_FILES"

      - name: Check RuboCop offenses
        run: |
          # Run RuboCop on the changed Ruby files
          OUTPUT=$(bundle exec rubocop $CHANGED_FILES)
          
          if [ $? -eq 0 ]; then
            echo "No RuboCop offenses found."
          else
            echo "RuboCop offenses found. Please fix them before merging."
            exit 1
          fi
