name: Rubocop

on:
  pull_request:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: Run Rubocop
        run: |
          bundle install
          bundle exec rubocop
