name: RuboCop

on:
  pull_request:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Check RuboCop offenses
        run: |
          OUTPUT=$(bundle exec rubocop --format simple)
          if echo "$OUTPUT" | grep -E '^(?:Offenses|==).*[1-9][0-9]* .*file' ; then
            echo "RuboCop offenses found. Please fix them before merging."
            exit 1
          fi

  merge-check:
    runs-on: ubuntu-latest
    needs: rubocop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Merge branches
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git merge --no-ff ${{ github.event.pull_request.base.ref }} --no-commit

      - name: Run RuboCop on merged code
        run: bundle exec rubocop

      - name: Check RuboCop offenses on merged code
        run: |
          OUTPUT=$(bundle exec rubocop --format simple)
          if echo "$OUTPUT" | grep -E '^(?:Offenses|==).*[1-9][0-9]* .*file' ; then
            echo "RuboCop offenses found in merged code. Please fix them before merging."
            git merge --abort
            exit 1
          else
            git commit -m "Merge branch '${{ github.event.pull_request.base.ref }}' into '${{ github.event.pull_request.head.ref }}'"
          fi
