name: RuboCop Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: List modified files
        id: files
        run: echo "::set-output name=modified_files::$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})"

      - name: Run RuboCop
        run: |
          modified_files=$(echo ${{ steps.files.outputs.modified_files }})
          if [ -n "$modified_files" ]; then
            bundle exec rubocop $modified_files
          else
            echo "No RuboCop offenses found in modified files."
          fi
