name: RuboCop Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: List modified Ruby files
        id: files
        run: echo "::set-output name=modified_files::$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.rb$')"

      - name: Run RuboCop on modified files
        run: |
          modified_files=$(echo ${{ steps.files.outputs.modified_files }})
          if [ -n "$modified_files" ]; then
            OUTPUT=$(bundle exec rubocop --format simple $modified_files)
            if echo "$OUTPUT" | grep -E '^(?:Offenses|==).*[1-9][0-9]* .*file' ; then
              echo "RuboCop offenses found in modified files. Please fix them before merging."
              exit 1
            else
              echo "No RuboCop offenses found in modified files."
            fi
          else
            echo "No modified Ruby files found."
          fi
