name: RuboCop

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v2
        with:
          ruby-version: 3.1.2

      - name: Install RuboCop
        run: |
          gem install rubocop

      - name: Get changed files
        id: changed-files
        run: |
          git diff --name-only HEAD HEAD~1 > changed-files.txt

      - name: Run RuboCop on changed files
        run: |
          bundle exec rubocop --only-files $(cat changed-files.txt)

      - name: Fail if there are RuboCop violations
        if: ${{ steps.rubocop.outputs.exit-code != 0 }}
        run: exit 1
