name: RuboCop Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: ${{ github.sha }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Get changed files
        id: changed-files
        run: |
          PR_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
          
          API_RESPONSE=$(curl -sSL -H "$AUTH_HEADER" "$PR_URL")
          echo "GitHub API Response: $API_RESPONSE"
          
          CHANGED_FILES=$(echo "$API_RESPONSE" | jq -r 'select(. | type == "array") | map(select(.filename | endswith(".rb"))) | .[].filename' | paste -sd " " -)
          echo "Changed Ruby files in the pull request: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run RuboCop
        run: bundle exec rubocop $CHANGED_FILES
