name: RuboCop Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: ${{ github.sha }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Get changed files
        id: changed-files
        run: |
          PR_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
          
          RESPONSE=$(curl -sSL -H "$AUTH_HEADER" "$PR_URL")
          echo "GitHub API response:"
          echo "$RESPONSE"
          
          CHANGED_FILES=$(echo "$RESPONSE" | jq -r '.[] | select(.filename | endswith(".rb")) | .filename')
          echo "Changed Ruby files in the pull request: $CHANGED_FILES"

      - name: Check RuboCop offenses
        if: ${{ steps.changed-files.outputs.CHANGED_FILES != '' }}
        run: |
          OUTPUT=$(bundle exec rubocop $CHANGED_FILES)
          if echo "$OUTPUT" | grep -E '^(?:Offenses|==).*[1-9][0-9]* .*file' ; then
            echo "RuboCop offenses found. Please fix them before merging."
            exit 1
          else
            echo "No RuboCop offenses found."
          fi
